apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  schedulerName: layer-scheduler
  containers:
  - name: test-pod
    image: Your Image
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 400m
        memory: 300Mi
